# Joint Summer Faculty Development Program 2020

##Machine Learning for Computer Vision
##June 29 to July 8, 2020

**Principal Coordinator - IIITDM Jabalpur : Co-Principal Coordinator - MNIT Jaipur**

**Particiapting Academies -** IIT Guwahati, MNIT Jaipur, NIT Patna, IIITDM Jabalpur 

# Assignment 2: Introduction to Python  

---



**Exercise 1:** Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
#Write your code here
import numpy as np
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


**Exercise 2:** Write a NumPy program to create an array with the values 100, 71, 113, 1050 and determine the size of the memory occupied by the array.


In [2]:
#Write your code here
import numpy as np
X = np.array([100, 71, 113, 1050])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[ 100   71  113 1050]
Size of the memory occupied by the said array:
16 bytes


**Exercise 3:** Write a NumPy program to get the powers ( x ^ 3 ) of an array values element-wise


Expected Output:
Original array
[1 2 3 4 5 ]
Output array: 
[ 1 8 27 64 125 ]

In [3]:
#Write your code here
import numpy as np
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


**Exercise 4:** Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.
Sample Output:
Original array:
[-1.3, -1.15, -0.1, 0.12, 1.7, 0.9, 1.1]

In [4]:
#Write your code here
import numpy as np
x = np.array([-1.3, -1.15, -0.1, 0.12, 1.7, 0.9, 1.1])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Original array:
[-1.3  -1.15 -0.1   0.12  1.7   0.9   1.1 ]
Floor values of the above array elements:
[-2. -2. -1.  0.  1.  0.  1.]
Ceil values of the above array elements:
[-1. -1. -0.  1.  2.  1.  2.]
Truncated values of the above array elements:
[-1. -1. -0.  0.  1.  0.  1.]


**Exercise 5:** Write a program in python to display prime numbers from x to y (here x and y are user given values).

In [5]:
#Write your code here
lower = int(input("Enter your lower value: "))
upper = int(input("Enter your upper value: "))


print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

Enter your lower value: 5
Enter your upper value: 30
Prime numbers between 5 and 30 are:
5
7
11
13
17
19
23
29


E&ICT, IIITDM Jabalpur