# Joint Summer Faculty Development Program 2020

##Machine Learning for Computer Vision
##June 29 to July 8, 2020

**Principal Coordinator - IIITDM Jabalpur : Co-Principal Coordinator - MNIT Jaipur**

**Particiapting Academies -** IIT Guwahati, MNIT Jaipur, NIT Patna, IIITDM Jabalpur 

# Assignment 1: Introduction to Python  

---



**Exercise 1.** Create following list:

data = [2,34,23,16,56,45,34,26,78,56,1,16]

Now delete the duplicate values and print the list in ascending order. 

In [1]:
#Write your code here
data = [2,34,23,16,56,45,34,26,78,56,1,16]

unique = []
for x in data:
    if x not in unique:
        unique.append(x)

print(unique)
unique.sort()
print(unique)

[2, 34, 23, 16, 56, 45, 26, 78, 1]
[1, 2, 16, 23, 26, 34, 45, 56, 78]


**Exercise 2:** Take five numbers as input from the user and save into a list. Find the maximum of the list and sort the data in descending order.

In [1]:
#Write your code here

In [11]:
number=[]
for i in range(5):
    x=input("Enter number")
    number.append(x)
print(number)

Enter number45
Enter number12
Enter number78
Enter number45
Enter number12
['45', '12', '78', '45', '12']


In [12]:
max(number)

'78'

In [17]:
number.sort(reverse=True)
number

['78', '45', '45', '12', '12']

**Exercise 4:**

(i) Generate two arrays A1 and A2 of size 5 X 4 and 3 X 4 respectively using np.random()

(ii) Join them and make an array A3 of 8 X 4. Now append random numbers ranging between from 0 to 5 to make the fourth array A4 of size 10 X 10. 

(iii) Print all the arrays and their transpose ( Transpose of 'A' can be obtained by 'A.T') 

In [3]:
#Write your code here
import numpy as np
print("Solution 4")
A1 = np.random.randint(1,high=10, size=(5, 4))
A2 = np.random.randint(1,high=20, size=(3, 4))

print("A1:  ", A1)

print("A2:  ", A2)

A3= np.concatenate((A1, A2))
print("A3:  ", A3)

A4 = np.random.randint(0,high=5, size=(10, 10))
print("A4:  ", A4)

Solution 4
A1:   [[6 6 6 5]
 [3 6 3 8]
 [4 7 7 5]
 [1 2 4 8]
 [8 5 6 4]]
A2:   [[18 16 19 18]
 [14 10 15 13]
 [ 4  6 13  4]]
A3:   [[ 6  6  6  5]
 [ 3  6  3  8]
 [ 4  7  7  5]
 [ 1  2  4  8]
 [ 8  5  6  4]
 [18 16 19 18]
 [14 10 15 13]
 [ 4  6 13  4]]
A4:   [[4 4 1 0 3 2 2 1 0 3]
 [4 3 2 4 2 3 0 1 3 0]
 [4 3 3 4 0 1 4 1 3 3]
 [4 0 4 1 2 3 4 4 0 0]
 [2 0 4 4 4 1 2 3 4 2]
 [1 0 1 1 1 4 1 2 3 3]
 [4 1 1 0 0 3 4 1 2 0]
 [2 3 1 4 0 0 1 3 3 4]
 [0 2 4 4 2 2 3 4 4 4]
 [0 2 0 3 3 4 0 3 2 4]]


**Exercise 5: Create two dictionaries.** 

The first dictionary 'name' will contain first name(key) of a person and its hash value(value). 
The Second will contain hash value(key) and mobile no(value). 


i) Add 5 entries.

ii) Delete two entries by taking the input from user as the first name.

ii) Add two entries by taking the input as the first name and mobile no. 

Hint: You can use remainder ( %) to obtain hash value. 

In [4]:
#Write your code here
name= {}
mobile={}
for i in range(0,5):
  first_name = input("First  Name : ")
  mobile_no = input("Mobile No : ")
  tmp= {(first_name, hash(first_name))}
  tmp2 = {(hash(first_name), mobile_no)}
  name.update(tmp)
  mobile.update(tmp2)
print(name)

print(mobile)



First  Name : Poornima
Mobile No : 99999999999
First  Name : Samir
Mobile No : 34832748327483
First  Name : Nishant
Mobile No : 38748324893274
First  Name : IIITDMJ
Mobile No : 3824832748324
First  Name : Jabalpur
Mobile No : 83748327483274
{'Poornima': -6884245282906144843, 'Samir': 7898564290890125232, 'Nishant': -1816605199999065794, 'IIITDMJ': 3360317370173672039, 'Jabalpur': -1896462043672267064}
{-6884245282906144843: '99999999999', 7898564290890125232: '34832748327483', -1816605199999065794: '38748324893274', 3360317370173672039: '3824832748324', -1896462043672267064: '83748327483274'}


In [5]:
for j in range(0,2):
  del_name= input("Name to delete:")
  name.pop(str(del_name))
  mobile.pop(hash(del_name))
print(name)
print(mobile)

Name to delete:IIITDMJ
Name to delete:Jabalpur
{'Poornima': -6884245282906144843, 'Samir': 7898564290890125232, 'Nishant': -1816605199999065794}
{-6884245282906144843: '99999999999', 7898564290890125232: '34832748327483', -1816605199999065794: '38748324893274'}


In [6]:
for i in range(0,2):
  first_name = input("First  Name : ")
  mobile_no = input("Mobile No : ")
  tmp= {(first_name, hash(first_name))}
  tmp2 = {(hash(first_name), mobile_no)}
  name.update(tmp)
  mobile.update(tmp2)
print(name)

print(mobile)

First  Name : E&ICT
Mobile No : 2938274
First  Name : Jaipur
Mobile No : 473276434
{'Poornima': -6884245282906144843, 'Samir': 7898564290890125232, 'Nishant': -1816605199999065794, 'E&ICT': -8051526715105851348, 'Jaipur': -2302335765711889365}
{-6884245282906144843: '99999999999', 7898564290890125232: '34832748327483', -1816605199999065794: '38748324893274', -8051526715105851348: '2938274', -2302335765711889365: '473276434'}


E&ICT PDPM IIITDM Jabalpur